/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticketbooking;

import org.ticketbooking.entities.Train;
import org.ticketbooking.entities.User;
import org.ticketbooking.services.TrainService;
import org.ticketbooking.services.UserBookingService;
import org.ticketbooking.util.UserServiceutil;

import java.io.IOException;
import java.sql.Array;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option  = 0;

        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }
        catch(IOException ex){
            System.out.println("There is something wrong!");
            return;
        }

        while(option != 7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();

            Train trainSelectedForBooking = new Train();

            switch(option){
                case 1:
                    System.out.println("Enter the User Name to sign up");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignUp, passwordToSignUp, UserServiceutil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceutil.hashPassword(passwordToLogin),new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }
                    catch(IOException ex){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBookings();
                    break;
                case 4:
                    // Search Trains
                    System.out.println("Type your source station");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String destination = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int index = 1;
                    for(Train t : trains){
                        System.out.println(index + "Train ID : " + t.getTrainId());
                        for(Map.Entry<String, String> entry : t.getStationTimes().entrySet()){
                            System.out.println("Station: " + entry.getKey() + "Time: " + entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1, 2, 3....");
                    trainSelectedForBooking = trains.get(scanner.nextInt());
                    break;

                case 5:
                    // Book a Seat
                    System.out.println("Select the seat by entering the row and column");
                    System.out.println("Enter the Row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the Column");
                    int column = scanner.nextInt();
                    System.out.println("Booking Your Seat...Please Wait...");

                    Boolean isSeatBooked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, column);
                    if(isSeatBooked == Boolean.TRUE){
                        System.out.println("Your Seat has been booked successfully! Enjoy the Journey..");
                    }
                    else{
                        System.out.println("This seat has already been booked. Please pick another one!!");
                    }
                    break;

                case 6:
                    // Cancel my Booking
                    System.out.println("Enter the ticket ID to cancel booking");
                    String ticketIDtoCancel = scanner.next();
                    //userBookingService.cancelBooking(ticketIDtoCancel);

                case 7:
                    break;
                default:
                    break;
            }


        }
    }
}


// JSON File - list of objects => ( {}, {}, {} )